version: "3.9"
services:
  client:
    image: ghcr.io/codeclubvn/introduce
    container_name: introduce
    restart: always
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    networks:
      - mynetwork
  nginx:
    image: nginx:1.21.1-alpine
    container_name: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - mynetwork
    depends_on:
      - client
networks:
  mynetwork:
    driver: bridge
